services:
  frontend:
    image: go-news-frontend:latest
    platform: linux/amd64
    build:
      context: .
      dockerfile: crates/bot/Dockerfile
    container_name: go-news
    restart: always
    working_dir: /app
    volumes:
      - ./config.toml:/app/config.toml:ro
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - backend
    networks:
      - internal_net

  backend:
    image: go-news-backend:latest
    platform: linux/amd64
    build:
      context: .
      dockerfile: crates/backend/Dockerfile
    container_name: go-news-backend
    restart: always
    working_dir: /app
    volumes:
      - ./data:/app/data
      - ./config.toml:/app/config.toml:ro
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    expose:
      - 8080
    networks:
      - internal_net

networks:
  internal_net:
    driver: bridge
    internal: false
